apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: v0.19.0
    helm:
      values: |
        global:
          openshift: true
          tlsDisable: false
        ui:
          enabled: true
        #openshift images
        injector:
          image:
            repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
            tag: "0.15.0-ubi"
          agentImage:
            repository: "registry.connect.redhat.com/hashicorp/vault"
            tag: "1.10.0-ubi"

        server:
          image:
            repository: "registry.connect.redhat.com/hashicorp/vault"
            tag: "1.10.0-ubi"
          route:
            enabled: true
            host: vault.apps.cluster-x9ffw.x9ffw.sandbox305.opentlc.com
          tls:
            termination: "reencrypt"
          # Mount a configmap containing custom script for bootstrap
          volumes:
            - name: vault-init
              configMap:
                name: vault-bootstrap
                defaultMode: 0420
            - name: vault-server-tls
              secret:
                secretName: vault-server-tls
          volumeMounts:
            - mountPath: "/vault/userconfig/script"
              name: "vault-init"
              readOnly: false
            - mountPath: "/vault/userconfig/vault-certs"
              name: "vault-certs"
              readOnly: false
          # Configure readiness probe to report "ready" even if Vault is uninitialized and sealed.
          # Useful when bootstrapping Vault for the first time.
          readinessProbe:
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"

          extraEnvironmentVars:
            VAULT_CAPATH: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            VAULT_ADDR: vault-internal.vault.svc.cluster.local:8200
          service:
            enabled: true
            annotations:
              #utilize OCP service-ca for certs
              service.beta.openshift.io/serving-cert-secret-name: vault-server-tls
        #Run post start config to init/unseal vault
        postStart:
          - "/bin/sh"
          - "-c"
          - "/vault/userconfig/script/bootstrap.sh"

          

  destination:
    namespace: vault
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
